AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AppPrefix:
    Description: Prefix for the application
    Type: String
    Default: osu-engr-expo

  DeplEnv:
    Description: Deployment environment
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  #Don't need to change or create for each lambda
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      ApiKeySourceType: HEADER
      Description: An API Gateway with a Lambda Integration
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Join ["-", [!Ref AppPrefix, !Ref DeplEnv, "rest-api"]]

  #Don't need to change or create for each lambda
  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: "application/json"
      RestApiId: !Ref RestApi
      Schema: {}

  #These are the API routes, create as needed
  HelloWorldApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      #parent resource, this one is root
      ParentId: !GetAtt RestApi.RootResourceId
      #name of the route
      PathPart: "hello-world"
      RestApiId: !Ref RestApi

  GetAllProjectsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      #parent resource, this one is root
      ParentId: !GetAtt RestApi.RootResourceId
      #name of the route
      PathPart: "get-all-projects"
      RestApiId: !Ref RestApi

  CreateNewProjectResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      #parent resource, this one is root
      ParentId: !GetAtt RestApi.RootResourceId
      #name of the route
      PathPart: "create-new-project"
      RestApiId: !Ref RestApi

  HelloWorldLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: hello-world-lambda.yaml
      TimeoutInMinutes: "60"
      Parameters:
        AppPrefix: !Ref AppPrefix
        DeplEnv: !Ref DeplEnv
        ResourceId: !Ref HelloWorldApiResource
        RestApiId: !Ref RestApi
    DependsOn:
      - HelloWorldApiResource

  GetAllProjectsLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: get-all-projects-lambda.yaml
      TimeoutInMinutes: "60"
      Parameters:
        AppPrefix: !Ref AppPrefix
        DeplEnv: !Ref DeplEnv
        ResourceId: !Ref GetAllProjectsResource
        RestApiId: !Ref RestApi
    DependsOn:
      - GetAllProjectsResource

  CreateNewProjectLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: create-new-project-lambda.yaml
      TimeoutInMinutes: "60"
      Parameters:
        AppPrefix: !Ref AppPrefix
        DeplEnv: !Ref DeplEnv
        ResourceId: !Ref CreateNewProjectResource
        RestApiId: !Ref RestApi
    DependsOn:
      - CreateNewProjectResource

  #Don't need to change or create for each lambda
  RestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Rest API deployment
      RestApiId: !Ref RestApi
    DependsOn:
      - HelloWorldLambdaStack
      - GetAllProjectsLambdaStack
      - CreateNewProjectLambdaStack

  #Don't need to change or create for each lambda
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref RestApiDeployment
      Description: Rest API stage v0
      RestApiId: !Ref RestApi
      StageName: "v0"
    DependsOn:
      - RestApiDeployment
